sudo: required
language: node_js
node_js: "8"

jobs:
  include:
    # - env:
    #     - ELECTRON_CACHE=$HOME/.cache/electron
    #     - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    - cache:
      directories:
      - node_modules
      - release-builds
      # - $HOME/.cache/electron
      # - $HOME/.cache/electron-builder
    - stage: Lint
      script: npm run lint
    - stage: Test
    # - stage: Coverage
    #   script: npm run coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

    - stage: Release
      script:
        - npm run electron-packager:mac
        - npm run electron-packager:linux

    - stage: Build and push tomomaster image (untagged)
      services:
        - docker
      install: skip
      before_script:
        - docker build -t tomochain/tomomaster .
      script:
        - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
        - docker tag tomochain/tomomaster tomochain/tomomaster:latest
        - docker push tomochain/tomomaster:latest
        - docker tag tomochain/tomomaster tomochain/tomomaster:$TRAVIS_BUILD_ID
        - docker push tomochain/tomomaster:$TRAVIS_BUILD_ID
      after_success:
        - curl -X POST $INFRA_IMAGE_REBUILD_HOOK

    - stage: Build and push tomomaster image (tagged)
      services:
        - docker
      install: skip
      before_script:
        - docker build -t tomochain/tomomaster .
      script:
        - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
        - docker tag tomochain/tomomaster tomochain/tomomaster:latest
        - docker push tomochain/tomomaster:latest
        - docker tag tomochain/tomomaster tomochain/tomomaster:$TRAVIS_TAG
        - docker push tomochain/tomomaster:$TRAVIS_TAG
      after_success:
        - curl -X POST $INFRA_IMAGE_REBUILD_HOOK

stages:
  - name: Lint
  - name: Test
  - name: Coverage
  - name: Release
  - name: Build and push tomomaster image (untagged)
    if: type != pull_request AND branch = master AND tag IS blank AND repo = tomochain/tomomaster
  - name: Build and push tomomaster image (tagged)
    if: type != pull_request AND branch =~ ^v AND tag IS present AND repo = tomochain/tomomaster
